# Codecov設定ファイル
# https://docs.codecov.com/docs/codecov-yaml

# カバレッジレポート設定
coverage:
  # カバレッジ精度（小数点以下2桁）
  precision: 2

  # カバレッジ範囲の設定
  range: 80..100

  # カバレッジステータス
  status:
    # プロジェクト全体のカバレッジ
    project:
      default:
        target: auto
        threshold: 0.5%
        base: auto

    # 変更部分のカバレッジ
    patch:
      default:
        target: 80%
        threshold: 0%

# Pull Requestへのコメント設定
comment:
  # コメント動作の設定
  layout: "header, diff, flags, components, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

  # カバレッジ情報の表示設定
  after_n_builds: 1

# カバレッジ計算から除外するファイル
ignore:
  - "tests/**/*"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "dist/**/*"
  - "coverage/**/*"
  - "node_modules/**/*"
  - "scripts/**/*"
  - "**/__mocks__/**/*"
  - "jest.config.js"
  - "prettier.config.js"
  - "eslint.config.mjs"

# カバレッジレポートのパース設定
parsers:
  javascript:
    enable_partials: true
